server:
  port: 80

spring :

  # Database setting
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: wanted
      password: wanted
    url: jdbc:mysql://localhost/wanted?useUniCode=yes&characterEncoding=UTF-8

  # JPA setting
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true